# Generated by Django 5.1.7 on 2025-03-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='state',
        ),
        migrations.AddField(
            model_name='game',
            name='player_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for players'), ('in_progress', 'Game in progress'), ('completed', 'Game completed')], default='waiting', max_length=20),
        ),
    ]
