# Generated by Django 5.1.7 on 2025-03-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_remove_game_created_at_remove_game_player1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('started', 'Started')], max_length=20),
        ),
    ]
