# Generated by Django 5.1.7 on 2025-03-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0004_game_players_alter_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_ready',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(default='waiting', max_length=20),
        ),
    ]
