# Generated by Django 5.1.7 on 2025-03-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0007_alter_game_current_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='curves',
            field=models.JSONField(default=list),
        ),
    ]
