# Generated by Django 5.1.7 on 2025-04-09 00:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0009_game_created_at_game_point_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='from_queue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='selected_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_preferences', models.JSONField(default=list)),
                ('ready', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('matched_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_by', to='Game.queueentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Entrée de file d'attente",
                'verbose_name_plural': "Entrées de file d'attente",
            },
        ),
    ]
